resource_types:
- name: ubuntu
  type: docker-image
  source:
    repository: docker.prod.pdc.digital.csaa-insurance.aaa.com/ubuntu-ruby-aws
    tag: latest


jobs:
- name: digital-certs
  plan:
  - get: digital-ssl-status-repo
    trigger: true
  - get: 24h
    trigger: true
  - task: current-certs
    file: digital-ssl-status-repo/ci/tasks/get_ssl_info/task.yml
    params:
      DATADOG_API_KEY: {{datadog_api_key}}

resources:
- name: digital-ssl-status-repo
  type: git
  source:
    uri: ssh://git@ssh.github.com:443/aaa-ncnu-ie/digital_ssl_status.git
    branch: master
    private_key: {{github_private_key}}
- name: 24h
  type: time
  source: {interval: 24h}
