---
N01PCF001:
  endpoint: N01PCF001.tent.trt.csaa.pri
  port: 443
mobile.api.dev:
  endpoint: mobile.api.dev.digital.pncie.com
  port: 443
mobile.api.digital:
  endpoint: mobile.api.digital.csaa-insurance.aaa.com
  port: 443
mypolciy.api.dev:
  endpoint: mypolicy.api.dev.digital.pncie.com
  port: 443
mypolicy.api.digital:
  endpoint: mypolicy.api.digital.csaa-insurance.aaa.com
  port: 443
mypolicy.bf:
  endpoint: mypolicy.bf.digital.pncie.com
  port: 443
mypolicy.dev:
  endpoint: mypolicy.dev.digital.pncie.com
  port: 443
mypolicy.digital:
  endpoint: mypolicy.digital.csaa-insurance.aaa.com
  port: 443
mypolicy.mo:
  endpoint: mypolicy.mo.digital.pncie.com
  port: 443
mypolicy.perf:
  endpoint: mypolicy.perf.digital.pncie.com
  port: 443
mypolicy.qa:
  endpoint: mypolicy.qa.digital.pncie.com
  port: 443
pawquote-UATAPPLB:
  endpoint: pasquote-UATAPPLB.tent.trt.csaa.pri
  port: 443
perf-wmcs:
  endpoint: perf-wcms.tent.trt.csaa.pri
  port: 443
prod-agencyport:
  endpoint: prod-agencyport.ent.rt.csaa.com
  port: 443
prod-wmcs:
  endpoint: prod-wcms.ent.rt.csaa.com
  port: 443
qa-wcms:
  endpoint: qa-wcms.tent.trt.csaa.pri
  port: 443
wildcard.digital.csaa-insurance:
  endpoint: anything.digital.csaa-insurance.aaa.com
  port: 443
wildcard.digital.pncie:
  endpoint: anything.digital.pncie.com
  port: 443
